In [1]:
%load_ext lab_black

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold

In [3]:
df = pd.read_csv("../Resources/full_data.csv").set_index("countries")

In [4]:
df

,year,year_id,country_id,regions,region_id,western_emerging,west_emerge_id,capital,latitude,longitude,fdi_in_usa_million,globalization_100,gdp_per_capita_usd,interaction_gdp,fdi_by_usa_million,interaction_us_fdi,stock_market_capitalization_gdp,interaction_stock_mkt,government_effectiveness,rule_of_law
countries,,,,,,,,,,,,,,,,,,,,
United Kingdom,1982,1,1,Europe,1,Western,1,London,51.5085,-0.1257,28447.0,78,9146.077357,713394.03380,27537.0,2147886.0,38.10340,2972.06520,1.88,1.63
United Kingdom,1983,2,1,Europe,1,Western,1,London,51.5085,-0.1257,32152.0,78,8691.518813,677938.46740,28086.0,2190708.0,46.12510,3597.75780,1.88,1.63
United Kingdom,1984,3,1,Europe,1,Western,1,London,51.5085,-0.1257,38387.0,78,8179.194441,637977.16640,29265.0,2282670.0,51.22640,3995.65920,1.88,1.63
United Kingdom,1985,4,1,Europe,1,Western,1,London,51.5085,-0.1257,43555.0,78,8652.216542,674872.89030,34066.0,2657148.0,72.24320,5634.96960,1.88,1.63
United Kingdom,1986,5,1,Europe,1,Western,1,London,51.5085,-0.1257,55935.0,78,10611.112210,827666.75240,36974.0,2883972.0,78.62570,6132.80460,1.88,1.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Liberia,2015,34,45,Africa,5,Emerging,2,Monrovia,6.3005,-10.7969,501.0,47,710.383858,33388.04131,1006.0,47282.0,0.42386,19.92142,-1.36,-0.86
Liberia,2016,35,45,Africa,5,Emerging,2,Monrovia,6.3005,-10.7969,479.0,47,714.623392,33587.29943,756.0,35532.0,0.42386,19.92142,-1.28,-0.95
Liberia,2017,36,45,Africa,5,Emerging,2,Monrovia,6.3005,-10.7969,457.0,48,698.701764,33537.68469,598.0,28704.0,0.42386,20.34528,-1.34,-0.95
Liberia,2018,37,45,Africa,5,Emerging,2,Monrovia,6.3005,-10.7969,466.0,48,677.322179,32511.46457,171.0,8208.0,0.42386,20.34528,-1.34,-0.99
Liberia,2019,38,45,Africa,5,Emerging,2,Monrovia,6.3005,-10.7969,461.0,48,621.892954,29850.86177,-94.0,-4512.0,0.42386,20.34528,-1.38,-1.00

In [5]:
target = "fdi_in_usa_million"

In [6]:
X = df.drop(
    [
        "fdi_in_usa_million",
        "year_id",
        "country_id",
        "regions",
        "region_id",
        "western_emerging",
        "west_emerge_id",
        "capital",
        "latitude",
        "longitude",
        "interaction_gdp",
        "interaction_us_fdi",
        "interaction_stock_mkt",
    ],
    axis=1,
).values
y = df[target].values

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24)

In [8]:
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)
y_test_pred = linear_regression.predict(X_test)
mean_squared_error(y_test, y_test_pred)

2061725253.6727967

In [9]:
decsion_tree = DecisionTreeRegressor()
decsion_tree.fit(X_train, y_train)
y_test_pred = decsion_tree.predict(X_test)
mean_squared_error(y_test, y_test_pred)

1113292553.8535752

In [10]:
random_forest = RandomForestRegressor()
random_forest.fit(X_train, y_train)
y_test_pred = random_forest.predict(X_test)
mean_squared_error(y_test, y_test_pred)

424422986.514929

In [11]:
# Pipeline the categorical Xs
# Boxplot for outliers
# Multicollinearity of Xs
# AOC Curve
# SHAP value and graph

In [12]:
# Model running and testing 1: Linear Multiple Regression (number of jobs)
# Model running and testing 2: Linear Multiple Regression with Interaction (number of jobs)
# Model running and testing 3: Decision Tree (parameters)
# Model running and testing 4: Random Forest (parameters)

In [13]:
# Best model with full data 1982-2019
# Try best model with lagged data by 1 yr
# Try best model with lagged data by 2 yr avg